### ISSUE TITLE
JS errors on first run

### ISSUE THREAD

**Issue by sdistefano** [MailOnline/videojs-vast-vpaid#1]
Hi,
interesting project! By following your instructions literally, I'm getting three JS errors on chrome:
```
Uncaught ReferenceError: vjs is not defined(anonymous function) @ videojs-vast-vpaid.js:2748(anonymous function) @ videojs-vast-vpaid.js:4823
vpaid.html:7 Uncaught ReferenceError: vjs is not defined(anonymous function) @ vpaid.html:7
video.js:59 Uncaught TypeError: this[a] is not a function
```
My head looks like this:
```
<script src="http://vjs.zencdn.net/4.12/video.js"></script>
<script src="videojs-vast-vpaid.js"></script>
<link href="http://vjs.zencdn.net/4.12/video-js.css" rel="stylesheet">
<link href="https://raw.githubusercontent.com/MailOnline/videojs-vast-vpaid/master/bin/videojs-vast-vpaid.css" rel="stylesheet">
```

**Comment by carpasse** [comment]
Hi @sdistefano I am sorry for the late response. We were not expecting people to try the plugin so soon. Still it is great that you have done so.

Also you have discovered a very unexpected problem. It seems that the mangled version of videojs is removing the global variable vjs and other functions from the player component. 

I have created an issue asking about this problem https://github.com/videojs/video.js/issues/2279 I can work around the vjs global variable but we need to have access to some of the player function in particular player.hasStarted to solve a problem we found when we updated videojs-contrib-ads.  https://github.com/videojs/videojs-contrib-ads/issues/93

I really wish I had a better solution but for the moment if you want to try the plugin, you will have to do so against an unmangled version of videojs.

I will try to find a solution for the problem as soon as possible. 

Thanks a lot for trying the plugin

**Comment by sdistefano** [comment]
Hi! Thanks a lot for the explanation. Yes, it's a pity we can't just use the videojs CDN and enjoying caching among multiple sites. I'll try embeeding the unmnagled videojs in my project for now then.
Thanks, I'll report back if I find anything

**Comment by ehoch** [comment]
Any update on this issue? I'm looking to use the CDN version as well..

**Comment by carpasse** [comment]
It seems that we won't have any problem with version 5.x.x but the problem will remain in version 4.x.x.
We are putting all our focus on supporting VPAID ads. Once we finally support them I will come back to this issue to try to find a solution.
