### ISSUE TITLE
Some build issues

### ISSUE THREAD

**Issue by orcaman** [MailOnline/videojs-vast-vpaid#10]
Hi guys,

Tried to pull this from master to test out locally, but I'm running into some issues.

- In `src/ads/vpaid/VPAIDFlashTech.js`, `line 27`, there is a reference to an object that is not defined anywhere in the code (`VPAIDFLASHClient` - note the upper case). Any ideas? 
- I had to download `video-js.css`, `xhook.js`, `swfobject.js`, `video.dev.js` and the vjs fonts from your live demo page (they were not included under the same directories in the master branch)

Cheers,
Or

**Comment by carpasse** [comment]
@orcaman are you using the lates version of the plugin??

We have added a [Running the Plugin](https://github.com/MailOnline/videojs-vast-vpaid/blob/master/README.md#running-the-plugin) section into the Readme.md. I hope this can help you run the demo locally.

**Comment by orcaman** [comment]
My bad, I forgot to "bower install". Cheers
