### ISSUE TITLE
Pausing the VPAID ad programatically 

### ISSUE THREAD

**Issue by orcaman** [MailOnline/videojs-vast-vpaid#11]
Hi guys,

Did you implement a JS API in your plugin to communicate with the VPAID object? for example, if I want to pause the VPAID ad programmatically - how do I do that? 

If I click the ad, and then I want to resume it by calling `play`, it seems that calling `player.play()` triggers the playing of the content, not the ad. 

Cheers,
Or

**Comment by carpasse** [comment]
Ideally we should be able to use the player api.
```
player.play(); //To play the ad
player.pause(); //To stop the ads
```
That way we can be consistent with VAST linear ads.
We are going to try to do investigate how to do so. We are also open for ideas in case somebody have any idea.

**Comment by carpasse** [comment]
It seems there is no easy way to use the player api to pause and play the adUnit. 
We publish an [object](https://github.com/MailOnline/videojs-vast-vpaid#playervast) in the player once the plugin has initialized. Would it work for you if we added a "pauseAd" and "playAd" methods?
Then you could execute
```
  player.vast.pauseAd()
```
to pause the adUnit, and 
```
 player.vast.resumeAd()
```
to play the previously paused ad.

In the case of VAST ads the methods would internally call 'player.pause()' and 'player.play()'. But on the case of VPAID the would call the 'pauseAd' and 'resumeAd' methods of the ad unit.

Would that work for you?

**Comment by orcaman** [comment]
Hi! Yes, this would definitely work.

**Comment by carpasse** [comment]
@orcaman We have finally added the change you requested.
If an ad is playing (after the 'vast.adStart' evt) we will add an adUnit object to the player.vast ob that will allow you to pause and resume the ad.

Please take a look at https://github.com/MailOnline/videojs-vast-vpaid#adunit

If it works for you please close the issue.

**Comment by orcaman** [comment]
Awesome. I'll test it in a few hours and let you know if it works as expected on my end.

**Comment by orcaman** [comment]
Cool. Verified. I've added some pause and resume functionality to the demo for VPAID and sent a PR, feel free to merge to discard.
