### ISSUE TITLE
Trouble playback on Iphone

### ISSUE THREAD

**Issue by whatvn** [MailOnline/videojs-vast-vpaid#118]
Hello, 

On safari Iphone, I am testing on Iphone 6s or with simulator 6s/6s plus, VAST and VPAID can not be played, when remote debug using safari develop extension, I dont see any error in console log. Video cannot start playback too, with black screen, no play button available. 

On Demo videojs-vast-vpaid site, I can see video can play well, even when ads cannot. 

Since I got no error log, I dont know how to provide detail information, can you provide some step to debug? 

Thanks,

**Comment by Fetz** [comment]
Hi @whatvn please provide us with the VAST tag (url) or VAST XML so we can try to debug.

When you play the video you should see some requests in the network tab, one of them if you click should show you some VAST XML.

```xml
<VAST version="2.0">
    <Ad>
        ...
    </Ad>
</VAST>
```

**Comment by whatvn** [comment]
@Fetz I use the same VAST tag as your demo: http://servedby.flashtalking.com/imp/1/31714;812030;208;xml;DailyMail;640x360VASTHTML5/?cachebuster=%%CACHEBUSTER%%

On Chrome desktop, firefox and safari desktop it's ok, but not on Iphone.

**Comment by Fetz** [comment]
I'm testing in iPhone Simulator (the iPhone 6s IOS 9.2)  and in a real iPhone device (6plus IOS 9.2) and both that  VAST tag and the VPAID Html5 Innovid test tag are working.

Do you have ad blocker on?
Did you press update button after you change the selectbox?

**Comment by whatvn** [comment]
No, I dont have adblocker. 
As I said, when testing on videojs-vast-vpaid demo page, ads and video worked, but when I use it with videojs on my implementable, it only works on desktop browser, not on Iphone safari (and chrome). 
The demo site works fine. Do you have any method to debug in this situation, I aslo catch adError event but did not get any error log. 

The video is freeze as well.

**Comment by Fetz** [comment]
Oh sorry now I get it.

First check if you are using the same version of videojs we are using in the demo.
In the browser console:

```js
> videojs.VERSION
< "4.12.15"
```

If it is, then sadly you have to do manual debugging... Would be cool to get some feedback so we can improve the debugging of the plugin

**Comment by whatvn** [comment]
Sorry this's problem I forget to talk about, I use videojs v5, which is the branch @wmcmurray has forked. Maybe that's the problem. 
The strange thing is, there's no error at all, so I cannot know how to start debugging...

**Comment by massa84** [comment]
can you try the new 5x branch #126 ?

**Comment by massa84** [comment]
the 5x branch has now been merged into master

**Comment by Fetz** [comment]
@whatvn you can check the demo here: http://mailonline.github.io/videojs-vast-vpaid/index_5.html.

If still have issue with iphone please reopen the issue
