### ISSUE TITLE
How to play a mid roll

### ISSUE THREAD

**Issue by rati592** [MailOnline/videojs-vast-vpaid#12]
I want to play the ad in every 2 mins interval. Please help me how to do this.

**Comment by rati592** [comment]
Also for preroll i am not able to play any vast or vpaid ad in http://mailonline.github.io/videojs-vast-vpaid/. Error VAST Error: on VASTClient.requestVastXML, HTTP request error with status '-1'

**Comment by carpasse** [comment]
We don't support midrolls for the moment. We have experience that error when people have an adBlocker or when the ad server does not set the proper CORS headers on the response.

Can you give us a test tag or copy the errors that appear on the console when you try to play the ad?

**Comment by rati592** [comment]
I am getting the error in your demo page http://mailonline.github.io/videojs-vast-vpaid/

**Comment by carpasse** [comment]
Ups we added a new configuration setting and set it wrong for the demo. Sorry for that.

The demo should be working now.

**Comment by rati592** [comment]
It's still showing me the same error

**Comment by carpasse** [comment]
Do you have a video ad blocker???

**Comment by carpasse** [comment]
Can you please open the dev tools and paste whatever it is on the console after the ad fails??

**Comment by carpasse** [comment]
It has been more than 8 days without response. 
@rati592 We have done some fixes regarding to CORS and the errors in the demo are solve.

If you still have this issue please reopen it.

**Comment by manumohant** [comment]
I have some CORS issue. Opened a ticket here[https://github.com/MailOnline/videojs-vast-vpaid/issues/190](url)

**Comment by manumohant** [comment]
I have some CORS issue, But with PreRoll ad. Issue opened [](https://github.com/MailOnline/videojs-vast-vpaid/issues/190). Please reply me asap
