### ISSUE TITLE
VPAIDFLASHClient is not defined

### ISSUE THREAD

**Issue by alex-phillips** [MailOnline/videojs-vast-vpaid#123]
I get an error when attempting to run a VAST ad with type `application/x-shockwave-flash`: `VPAIDFLASHClient is not defined`.

It is happening on line 21 of `VPAIDFlashTech.js`. It is referencing the object but that object is never defined anywhere.

**Comment by Fetz** [comment]
Can you replicate in the demo, or in implementation?

Are you using any package manager?

If not you can use bower or npm to install the necessary files or you can get here:
https://github.com/MailOnline/videojs-vast-vpaid/tree/RELEASE/bin

**Comment by alex-phillips** [comment]
@Fetz So I believe my issue is that the videojs-5x branch does not generate the proper `bin` files. I thought `gulp build --env production` should generate these for me. Is that no longer the case?

**Comment by Fetz** [comment]
We still working on that branch, so please for now avoid that branch. I will let you know when to use it.

**Comment by alex-phillips** [comment]
Is there some ETA, even a guess? We've been developing our new player with the v5 branch here (https://github.com/MailOnline/videojs-vast-vpaid/pull/107) and it has been working fine so far. Is there anything we can do to help move things along? We're hoping to launch very soon.

**Comment by Fetz** [comment]
@massa84 is only fixing the sourcemaps generation for both ugliyfied version and normal version and a code review.

**Comment by alex-phillips** [comment]
Gotcha. Thanks for the info!

**Comment by massa84** [comment]
@alex-phillips should work now !

I haven't looked into some of the videojs5 specific issues yet (like the issue on mobile devices) but everything should be more or less ok.
This is a complete refactor to commonjs (browserify) approach and with support for video.js 5

**Comment by alex-phillips** [comment]
Awesome, thanks @massa84! Will test it out with our code now. Appreciate all the work.

**Comment by alex-phillips** [comment]
@massa84 Is there a way to make errors a bit more visible? There is an error that's being triggered with the current message `timeout waiting for event "AdLoaded"` but nothing in the code really shows what actually 'triggers' that event. Any thoughts?

**Comment by Fetz** [comment]
@alex-phillips regarding VPAID most of this logic lives in this 2 repos:

https://github.com/MailOnline/VPAIDHTML5Client
https://github.com/MailOnline/VPAIDFLASHClient

But in VPAID most of the events are trigger by the ad itself.

[VPAID diagram page 17](http://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf)

In the case of `AdLoaded` is fired after (the ad loads all the things he needs) after we call the method initAd.

**Comment by alex-phillips** [comment]
Gotcha. So I guess it's safe to assume that this particular ad for some reason isn't triggering the `AdLoaded` event. I'm guessing the VAST XML doesn't list the events that should be present? I can provide the culprit XML if that helps at all.

**Comment by Fetz** [comment]
You can share the xml/tag so we can debug if there is any particular issue with plugin code or an issue with the particular ad
