### ISSUE TITLE
< ie11 ad clickthrough not working and seek bar is seekable

### ISSUE THREAD

**Issue by LastStarfi9hter** [MailOnline/videojs-vast-vpaid#132]
Hi,

Cheers for the v5 upgrade. Spotted a couple of old IE issues.

loaded on ie11 everything functions correctly.
I'm sure old IE isn't at the top of the priority list but if it is an easy fix...
Using the same ad call as in the default demo.

http://staging.chookdigital.net/dev.chook.com.au/greg/chooktv/git-test/

Thanks!

**Comment by Fetz** [comment]
I checked your page and looks like is working in ie10 only if you click the play icon in top left corner  (if you click in the center of the video doesn't work). I checked and looks like this element `.vjs-text-track-display` is blocking the click event in the `.vjs-poster`.

[IE10 doesn't support pointer events](http://caniuse.com/#feat=pointer-events)

so I think the issue you having is with the version of videojs you are using. If text-track is not important for you, you could hide for old < ie11
