### ISSUE TITLE
VideoJS 5 demo broken on iOS

### ISSUE THREAD

**Issue by nickygerritsen** [MailOnline/videojs-vast-vpaid#137]
It seems the videoJS 5 demo is broken on iOS. The 4 demo does work.

If desired, I could hook my iPhone up to my laptop and find out console output.

**Comment by Fetz** [comment]
the css class from videojs `vjs-using-native-controls` is hiding the poster of videojs (probably because is IOS videojs hides the poster) and our black poster (to fix some issues we having in some old browsers) is blocking the click. I will check was is the best solution

**Comment by Fetz** [comment]
sorry closed the issue automatically with the commit. Should be fixed when I updated the demo page.

**Comment by Fetz** [comment]
I updated the demo for videojs5x, let me know if is fixed or if you find any other issue

**Comment by nickygerritsen** [comment]
Yep it works now :)
