### ISSUE TITLE
Cannot Play vpaid ads on my browser !!

### ISSUE THREAD

**Issue by ankurhora** [MailOnline/videojs-vast-vpaid#141]
Hi,

i am trying to play the ads on my system but not from localhost but direct pasting the file in my browser . It doesnot pLAY ads but instead i get this error in my console 
"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null')".

I tracked and changed this in my videojs_5.vast.vpaid.js in the postMessage function from {{origin}} to *
Now the error doesnot sow up but still i am unable to load ads 
"AD ERROR: VAST Error: timeout while waiting for the video to start playing "
.

**Comment by Fetz** [comment]
[VPAIDHTML5](https://github.com/MailOnline/VPAIDHTML5Client) is using postMessage to send events between iframe and top window. And there is a check [here](https://github.com/MailOnline/VPAIDHTML5Client/blob/master/js/VPAIDHTML5Client.js#L107) to confirm that the message is coming [from a valid orign](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Security_concerns)
