### ISSUE TITLE
Skip button

### ISSUE THREAD

**Issue by halibegic** [MailOnline/videojs-vast-vpaid#206]
Hi,

Is it possible to add skip button after x seconds?

**Comment by belimawr** [comment]
I would like to know that as well. Is there any plans to implement this feature in the near future?

**Comment by Fetz** [comment]
We are only showing the skip button when we receive (for example in VPAID *AdSkippableState*).

This event AdSkippableState is only supported in VPAID 2.0, so in VPAID 1.0 maybe skipAd will not work.

As well if somehow skip the ad before that event, will count probably as canceledAd, so you will not get any money...

But if you still want to have hability to do this, we can add an way to force skip button to appear after x time, but that will come at cost of revenue

**Comment by halibegic** [comment]
Ok, thank you.
