### ISSUE TITLE
on vast timeout error plugin not removed

### ISSUE THREAD

**Issue by LastStarfi9hter** [MailOnline/videojs-vast-vpaid#22]
Hey,

Every so often I'll get:
AD ERROR: VAST Error: timeout while waiting for the video to start playing VASTError {message: "VAST Error: timeout while waiting for the video to start playing", code: 402} undefined

The plugin doesn't seem to remove itself at this point. '.vast-blocker' stays up and blocks normal video interaction.

Using url http://ad5.liverail.com/?LR_PUBLISHER_ID=58163&LR_SCHEMA=vast2.

Thanks!

**Comment by LastStarfi9hter** [comment]
latest release looks to have resolved this :)

**Comment by Guiguillermo** [comment]
Hello,

I got the same problem, so I tried to update the scripts with the last version but it still doesn't work.
I receive the vast.adStart event and then, I receive the vast.adError event, the same error than you.
Sometimes, the video is playing during a few seconds and then I receive the error event.

Thanks !
