### ISSUE TITLE
http://mailonline.github.io/videojs-vast-vpaid/ is broken

### ISSUE THREAD

**Issue by jhenkens** [MailOnline/videojs-vast-vpaid#251]
Seems the latest gh-pages deploy broke things.

**Comment by Fetz** [comment]
@jhenkens thanks for letting us know, fixed with this commit: https://github.com/MailOnline/videojs-vast-vpaid/commit/d760f7d92ee0cb3cd6c2c7448281724e2dd928b1

Is working now http://mailonline.github.io/videojs-vast-vpaid/index_5.html
