### ISSUE TITLE
Firefox timeout errors: VAST Error: on VPAIDAdUnitWrapper.waitForEvent

### ISSUE THREAD

**Issue by iq-dot** [MailOnline/videojs-vast-vpaid#276]
Hi all,

I am constantly getting timeout errors for the Ad to play which happens on Firefox but not on Chrome or Safari.

AD ERROR: VAST Error: on VPAIDAdUnitWrapper.waitForEvent, timeout while waiting for event 'AdStarted'

So the XML gets retrieved but times out while trying to play the Ad, could this be flash related?

I noticed though if I wait a little a bit before clicking to play... so there may also be something related to the initialisation.

**Comment by iq-dot** [comment]
Is there any way to know that the vastClient is fully ready and initialised? Like an event or a callback?

**Comment by mmilleruva** [comment]
I am getting this error as well, but for HTML5 ads. I think it is VAST related. The demo page for this repo appears broken for all of the VAST ads.

**Comment by memoo89** [comment]
I am also getting this issue. Is that an issue related to the plugin or the provide ad tag?

**Comment by iq-dot** [comment]
I got this working by doing a flash detection, if flash is enabled (and not blocked) then listen to the 'change' event of window.vpaid_video_flash_tester. Once that event is fired, you can safely load/play your content.

Note that the 'change' event will not fire if flash is blocked or if plugin is not installed, hence why you can't change hook into to it, you need to do a flash detection first.
