### ISSUE TITLE
Vpaid 2 support

### ISSUE THREAD

**Issue by bkolo** [MailOnline/videojs-vast-vpaid#28]
Does this plugin support VPAID 2 (javascript VPAID).

Here is an example ad tag from Liverail.
http://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid&LR_ALLOW_RETRY=3&LR_FORMAT=application/x-shockwave-flash;application/javascript&LR_VIDEO_POSITION=0,50%,100%&LR_AUTOPLAY=1&LR_VIDEO_ID=[LR_VIDEO_ID]&LR_TITLE=[LR_TITLE]&LR_DURATION=32&CACHEBUSTER=[CACHEBUSTER]

thanks!
Bob

**Comment by Fetz** [comment]
Hi @bkolo,

Yes we support you can test here:

http://mailonline.github.io/videojs-vast-vpaid

- select VPAID tag
- add the tag in the input
- press update
- play video

If you want to test your tag to test the JS please remove the application/x-shockwave-flash, to force the request to only return the js VPAID, tag below:

http://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid&LR_ALLOW_RETRY=3&LR_FORMAT=application/javascript&LR_VIDEO_POSITION=0,50%,100%&LR_AUTOPLAY=1&LR_VIDEO_ID=[LR_VIDEO_ID]&LR_TITLE=[LR_TITLE]&LR_DURATION=32&CACHEBUSTER=[CACHEBUSTER]

If not it will play the flash VPAID first.

**Comment by bkolo** [comment]
Thanks Luis.  I don't think I will be able to change the way Liverail and
other Ad Tech companies return their VAST ads to remove the Flash Tag.  It
looks like they will be returning both the Flash and Javascript mediafiles
to support both options.  Do you think it is worth the effort for the
plugin to look at all MediaFiles returned from the ad server and pick the
best one that the plugin can play when there are multiple options?

regards,
Bob

**Comment by Fetz** [comment]
Hi @bkolo, I was showing how you could preview the JS VPAID.

Regarding *'pick the best one'*, what we are doing now is checking what user supports and playing it.  We are following the order in the mediafile tag.

If the first mediafile is flash tech than we check if the user can play, if yes we play it, if not we go to the next until there is no more media files available.

We could try to make it preferable to play JS ad's, or ad an option to choose what tech is preferable when the user supports more than one tech

**Comment by bkolo** [comment]
Thanks Luis.  Here is an example ad tag that contains both flash and
javascript.
I guess something is failing then.  This one fails to load.
If the vast returns ONLY the javascript, it does in fact work.

Test TAG:
http://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_CAMPAIGN_ID=229&LR_SCHEMA=vast2-vpaid&LR_ALLOW_RETRY=3&LR_FORMAT=application/x-shockwave-flash;application/javascript&LR_VIDEO_POSITION=0,50%,100%&LR_AUTOPLAY=1&LR_VIDEO_ID=%5BLR_VIDEO_ID%5D&LR_TITLE=%5BLR_TITLE%5D&LR_DURATION=32&CACHEBUSTER=%5BCACHEBUSTER%5D

Thanks for the great support!

Bob

**Comment by Fetz** [comment]
I'm testing in chrome and is working in my machine. In firefox is being blocked by CORS. Please check the browser the console

**Comment by bkolo** [comment]
Thanks for the response.  I am using Chrome and do know about the CORS
issues with Firefox.

When using an ad tag that returns both flash and javascript in Chrome, with
Flash DISABLED.

The console shows:
'HTMLVideoElement.webkitDisplayingFullscreen' is deprecated. Please use the
'fullscreenchange' event instead.
videojs.vast.js:286 AD ERROR: user don't support flash or doesn't have the
minimum required version of flash 10.1.0 Error: user don't support flash or
doesn't have the minimum required version of flash 10.1.0
    at
http://mailonline.github.io/videojs-vast-vpaid/scripts/videojs-vast-vpaid.js:409:26
VASTResponse {_linearAdded: true, ads: Array[1], errorURLMacros: Array[0],
impressions: Array[0], clickTrackings: Array[0]…}


When I ENABLE flash in Chrome, the Flash based ad loads and plays.
Since Chrome will be disabling Flash in September, I think this will be an
issue soon.

**Comment by Fetz** [comment]
@bkolo yes just replicated. We will fix the bug

**Comment by Fetz** [comment]
commit related 6a89671da93c61b42546b0a8014f3715020defe6

**Comment by Fetz** [comment]
this issue will be fixed in the next release

**Comment by Fetz** [comment]
In the demo page you can test the fix

**Comment by bkolo** [comment]
Thanks Fetz.  So now, what I experience (with Chrome Disabled) and an ad tag that has both Flash and Javascript media files (which looks to be the way ad tech will handle the migration from Flash to JS in September) is the Flash Disabled placeholder for Chrome.  I think the user experience would benefit from using the Javascript media file so that the ad just plays.  

I guess the test whether flash is installed is concluding that flash is in fact installed but disabled. I'm not sure what the best way to handle that is but this will be what happens in September when Chrome disables Flash.

**Comment by Fetz** [comment]
@bkolo I don't know if I really get it but the validation for testing if the browser supports or not flash is:
 - is flash available*?
 - is the version the one plugins needs?
 - then we play

*if is in installed and is enabled

**Comment by Fetz** [comment]
I will close this issue (if something is not done please reopen again)
