### ISSUE TITLE
Unable to see video ads before video.

### ISSUE THREAD

**Issue by ssynapse** [MailOnline/videojs-vast-vpaid#291]
Hi,
I used LKQD Ad server, with following Ad tag.
https://v.lkqd.net/ad?pid=367&sid=331975&output=vastvpaid&support=html5flash&execution=instream&placement=preroll&playinit=user&volume=75&width=[WIDTH]&height=[HEIGHT]&dnt=[DO_NOT_TRACK]&pageurl=[PAGEURL]&contentid=[CONTENT_ID]&contenttitle=[CONTENT_TITLE]&contentlength=[CONTENT_LENGTH]&contenturl=[CONTENT_URL]&rnd=[CACHEBUSTER]

But i am not able to see ad before or after or in between video with this tutorial. Please let me know how to use this plugin to run Ads within the videos.

Thanks

**Comment by ssynapse** [comment]
Hi,
I used LKQD Ad server, with following Ad tag.
https://v.lkqd.net/ad?pid=367&sid=331975&output=vastvpaid&support=html5flash&execution=instream&placement=preroll&playinit=user&volume=75&width=[WIDTH]&height=[HEIGHT]&dnt=[DO_NOT_TRACK]&pageurl=[PAGEURL]&contentid=[CONTENT_ID]&contenttitle=[CONTENT_TITLE]&contentlength=[CONTENT_LENGTH]&contenturl=[CONTENT_URL]&rnd=[CACHEBUSTER]

But i am not able to see ad before or after or in between video with this tutorial. Please let me know how to use this plugin to run Ads within the videos.

Thanks

**Comment by peterSnowQIU** [comment]
Is the problem that video ads can't display has been solved?
