### ISSUE TITLE
Recomendation for implementing VideoJs-vast-plugin with Playlists?

### ISSUE THREAD

**Issue by bkolo** [MailOnline/videojs-vast-vpaid#31]
Can you suggest the best way to implement playlists with your plugin?
Ideally, an ad opportunity would be available at the beginning of each new video in the playlist.

regards,
Bob

**Comment by Fetz** [comment]
@bkolo you can see an example of that in our page:

http://www.dailymail.co.uk/news/article-3211338/House-millionaires-resort-John-Lennon-bought-bungalow-aunt-raised-son-goes-sale-4-5million.html#video

I wasn't involved on that but I think videoplayer has a method that allows you to change the video src. So the moment you change the src and you play it, the plugin should try to preroll the ad's.
