### ISSUE TITLE
VPAID - several events are not working

### ISSUE THREAD

**Issue by yonida** [MailOnline/videojs-vast-vpaid#36]
1. `adUnit.on('AdClickThru', function (data)` - data is undefined and data.url fails. 
2. `adUnit.on('AdVolumeChange', function ()` is never called.

**Comment by Fetz** [comment]
Can you send or the vast/vpaid tag or a url with your implementation

**Comment by yonida** [comment]
I'm just using your demo with the VPAID spotX test tag - just put a debugger in `AdClickThru` and `AdVolumeChange` callbacks.

**Comment by Fetz** [comment]
I tested other ads and they are throwing correctly those events. Sadly some of the tests ads aren't fully implemented...

If you test VPAID Flash Brainient  Preroll Linear Button is triggering the events 'AdClickThru' and 'AdVolumeChange'

**Comment by yonida** [comment]
Thanks!

**Comment by kwolniak** [comment]
@yonida @Fetz  How can i bind to this AdClickThru event?
```player.on('AdClickThru', function (data) {
                    console.log(data);
                });```

or some other way?
