### ISSUE TITLE
AdParameters not getting passed in Ad Tag

### ISSUE THREAD

**Issue by bkolo** [MailOnline/videojs-vast-vpaid#38]
This ad network is not working correctly with plugin.
http://dev.testing.optimatic.com/optivpaid/examples/vpaid/outputXML.ashx?f=optimatic-vpaid.xml

The ad loads and initializes but when it attempts to load  AdParameters from the VAST it fails.

thanks!

**Comment by Fetz** [comment]
I replicated and will be fixed tomorrow

**Comment by bkolo** [comment]
Great. Thanks!

**Comment by Fetz** [comment]
You can check in our demo page the fix:

http://mailonline.github.io/videojs-vast-vpaid

**Comment by bkolo** [comment]
Yes. I can confirm that the demo is working now with adparameters.
thanks!
Bob
