### ISSUE TITLE
Sourcecode for VPAIDFlash.swf ?

### ISSUE THREAD

**Issue by Horcruxes** [MailOnline/videojs-vast-vpaid#39]
Hi, I've been tested this plug in for a while and on the demo link it looks all great.

But when I try to do a minimum setup, following the instructions gives me a bit issue with the Play/Pause Ad. and it seems like not every VPAID call back (e.g. AdClickThru) is getting connected by this plugin?

I am wondering is it possible to also include the ActionScripts for the VPAIDFlash.swf so that I could perform some debug by myself?

**Comment by Fetz** [comment]
Hi,

The issue should be the related to this issue:

https://github.com/MailOnline/videojs-vast-vpaid/issues/36

But of course the best way to guarantee is testing yourself.

If you need to debug in a deeper level the VPAID's, you can check in this repos:

For flash:

https://github.com/MailOnline/VPAIDFLASHClient

(you don't need flash builder or flash develop to build the swf you can build with the gulp scripts available)

For js:

https://github.com/MailOnline/VPAIDHTML5Client
