### ISSUE TITLE
Improve the release process

### ISSUE THREAD

**Issue by Fetz** [MailOnline/videojs-vast-vpaid#43]
- change to from carlos account to mailonline account the release
- fix duplicated release
- when released do `npm publish` automatically
- remove from the main branch the bin files

**Comment by carpasse** [comment]
I have fixed the duplicated issue :)

**Comment by sithmel** [comment]
npm publish now happens on every tag. We now use a generic mol-automation user for tasks triggered by CI.

**Comment by carpasse** [comment]
Great job @sithmel
