### ISSUE TITLE
update adunit when the video grows or shrink when playing an ad

### ISSUE THREAD

**Issue by Fetz** [MailOnline/videojs-vast-vpaid#5]
In responsive full videos, or in phones when the viewport is rotated, we need to update the vpaid ad's size

**Comment by Fetz** [comment]
we could listen simply to window resize or/and orientation change

or we want something more flexible maybe using this:
https://github.com/sdecima/javascript-detect-element-resize
or this:
http://www.backalleycoder.com/2013/03/18/cross-browser-event-based-element-resize-detection/

**Comment by carpasse** [comment]
I would listen to the 'resize' and 'orientationchange' events that is probably the most common use.

**Comment by Fetz** [comment]
but in cases the video is resized in by script's maybe is better to create some api that allow's the user maybe to control this instead of we assuming what the user's wants.

**Comment by carpasse** [comment]
we could listen to a custom player event like 'resize.ads' and update the vpaid ad's size.
I would still listen to the 'orientationchange' and 'resize' events though.

**Comment by Fetz** [comment]
I think that event is too generic, maybe we should prefix with 'vast' or something like that.

And if we listen to this events we should at least ad some flag in the configuration of the plugin to disable if for some reason it needs a different implementation or they don't need the plugin to resize.

**Comment by carpasse** [comment]
how about 'vast.resize'??
Regarding to the configuration option, it makes sense.

**Comment by Fetz** [comment]
ok I will implement like that
