### ISSUE TITLE
video.dev.js to video.js

### ISSUE THREAD

**Issue by junaidtufail** [MailOnline/videojs-vast-vpaid#50]
Videojs vast vpaid plugin works with video.dev.js. I want it working with video.js the production version. 
is it possible?

**Comment by carpasse** [comment]
This was a problem in the past due to the videojs-contrib-ads but we are no longer using it. 
I have done a quick test in our demo page and everything is seems fine.
So I would say **yes it is possible**

Please reopen the issue if you encounter any problem with the production version of videojs
