### ISSUE TITLE
Pre-roll ad is not displaying before video

### ISSUE THREAD

**Issue by Happelation** [MailOnline/videojs-vast-vpaid#55]
When I update the form with my VAST/VPAID tag on this site, it shows my ad and works, but when I download the files and implement on my site, then no pre-roll ad shows, and video plays shortly after a blank screen. Where do I need to put the ad tag without sending it through the form on this page, and if there is an example without all of the inputs on this page that will work too

**Comment by Fetz** [comment]
Can you send a url with your example that doesn't work?

As well check our github page files here:

https://github.com/MailOnline/videojs-vast-vpaid/tree/gh-pages

**Comment by carpasse** [comment]
@Happelation Have you followed all the steps from https://github.com/MailOnline/videojs-vast-vpaid#integration-with-videojs ??

Do you have any error on your console, if so can you please paste it here?

**Comment by carpasse** [comment]
I forgot to mention the ad tag needs to be specified in the url option https://github.com/MailOnline/videojs-vast-vpaid#url

**Comment by carpasse** [comment]
We have changed the name of the url option to adTagUrl. You can still use it as url but it is deprecated.

**Comment by Happelation** [comment]
This is working now, thanks @carpasse and @Fetz

**Comment by carpasse** [comment]
Great let us know if you encounter any other problem
