### ISSUE TITLE
SpotX VPAID Tags Don't Work

### ISSUE THREAD

**Issue by orcaman** [MailOnline/videojs-vast-vpaid#6]
Hi there,

Trying to use the SpotX Test tag, does not seem to work:
http://search.spotxchange.com/vast/2.00/79391?VPAID=1&content_page_url=test.com&cb=3202405928168446&player_width=300&player_height=250

You can test it wit the Brightroll test VPAID player:

http://testplayer.brightroll.com/?adInitEmptySize=false&config=http%253A%252F%252Fsearch.spotxchange.com%252Fvast%252F2.00%252F79391%253FVPAID%253D1%2526content_page_url%253Dtest.com%2526cb%253D3202405928168446%2526player_width%253D300%2526player_height%253D250&size=640x360&scout=true

Thanks,
Or

**Comment by carpasse** [comment]
@orcaman thanks for the test tag.

We are taking a look at it.

**Comment by carpasse** [comment]
@orcaman We have created a PR to fix the issue you are having with spotX tags.
Once is merged we will create a new Release
