### ISSUE TITLE
Video Not Autoplay After VAST3 Ads

### ISSUE THREAD

**Issue by junaidtufail** [MailOnline/videojs-vast-vpaid#61]
After ad is completing , video does not autoplay. I need to click video to play but it should autoplay after ad. Please see following example url for issue.
http://wptester.info/video-js/demo.html

**Comment by Fetz** [comment]
I tested your demo page in mac with a safari browser Version 8.0.8 (10600.8.9) and Chrome Version 45.0.2454.93 (64-bit) and the video is playing after the ad.

Can you please send us more info about browser/os?

PS: I notice the server is slow, could be that is loading the video?

**Comment by carpasse** [comment]
I have also tested it on a nexus5/android 5.1.1 and it is also working.
Could it be that your server is too slow?

**Comment by junaidtufail** [comment]
Not working on firefox on both MAC / Windows for me

**Comment by carpasse** [comment]
I can reproduce the bug. It does not happen in our demo but I think the problem has to do with the 'canplay' evt. This problem has already being asked on [stackoverflow](http://stackoverflow.com/questions/10235919/the-canplay-canplaythrough-events-for-an-html5-video-are-not-called-on-firefox). Working on a fix for it.

@junaidtufail Thanks for reporting it

**Comment by carpasse** [comment]
I just did a [release](https://github.com/MailOnline/videojs-vast-vpaid/releases/tag/0.1.16) containing  a fix for the firefox double tab issue. 
@junaidtufail can you please update the plugin in your demo page and see if works in firefox?

**Comment by junaidtufail** [comment]
I have updated my demo page and it is working fine now on windows firefox now. i will test on MAC Firefox also and tell you. 

Waiting for Mid rolls and post rolls update from you. :)

you guys developed awesome plugin.

**Comment by carpasse** [comment]
@junaidtufail thanks for your comments.

Sorry about the delay on mid and post rolls we are trying to stabilise preroll ads before starting with them.
Hopefully we should be able to start working on them in a week or two.

Did it work on Mac Firefox for you? I just tested on mine and it is working!
If it does for you, can you please close the issue?

**Comment by junaidtufail** [comment]
Yes it works fine on MAC firefox also.

Thanks,
