### ISSUE TITLE
How does code get into ./bin

### ISSUE THREAD

**Issue by kahwee** [MailOnline/videojs-vast-vpaid#67]
I saw that `gulp build` seem to create the `./dev` directory, how does the code then get released into `./bin`? Is it manually copied?

**Comment by Fetz** [comment]
Is done by [travis CI videojs-vast-vpaid](https://travis-ci.org/MailOnline/videojs-vast-vpaid).

https://github.com/MailOnline/videojs-vast-vpaid/blob/master/.travis.yml

the script that does the job is this one:
https://github.com/MailOnline/videojs-vast-vpaid/blob/master/scripts/release

When you push the code to the branch (major/minor/patch), travis will execute the release script and the bin code will be updated in the branch [RELEASE](https://github.com/MailOnline/videojs-vast-vpaid/tree/RELEASE)

**Comment by kahwee** [comment]
Thanks!
