### ISSUE TITLE
VAST Wrapper Ads Not Working

### ISSUE THREAD

**Issue by bkolo** [MailOnline/videojs-vast-vpaid#7]
It looks like you haven't setup support for VAST Wrappers yet.
Here is some documentation about this standard VAST.  Wrappers simply allow ad serving technology to redirect to outer VAST ads while subscribing to events along the way.

Here is some info:
http://support.brightcove.com/en/video-cloud/docs/vast-wrapper-ads

**Comment by carpasse** [comment]
@bkolo VAST Wrappers are supported we handle all that logic when we get the VAST response.

please look at the vast client code https://github.com/MailOnline/videojs-vast-vpaid/blob/master/src/ads/vast/client/VASTClient.js#L113

All the VAST Wrapper related logic is fully tested on the VAST client specs https://github.com/MailOnline/videojs-vast-vpaid/blob/master/test/ads/vast/client/VASTClient.spec.js

Why do you think we have no support for VAST Wrappers?? as a matter of fact, some of the sample tags on our demo do send wrappers on the first and second vast request.

We do have a WRAPPER_LIMIT of 5 to prevent infinite loops.

Have you encountered any problem with a VAST Wrapper in our plugin??

**Comment by bkolo** [comment]
Thanks for the quick response.  I stumbled upon your project and tested it with an ad tag:
http://syndication.videodetective.com/vast.ashx?customerid=69249&partnerid=76056&reportingtag=vdtitlepage&domain=www.videodetective.com&LR_SCHEMA=vast2-vpaid&TITLE=Trainwreck&VIDEOID=918133&DESCRIPTION=Since%20she%20was%20a%20little%20girl%2C%20it%E2%80%99s%20been%20drilled%20into%20Amy%E2%80%99s%20(Schumer)%20head%20by%20her%20rascal%20of%20a%20dad%20(Col&BITRATE=high&AUTOPLAY=1&MUTED=0&URL=http%3A%2F%2Fwww.videodetective.com%2Fmovies%2Ftrainwreck%2F918133&cb=300352861161874600&playerwidth=null&playerheight=null

which returned the error: 
AD ERROR: VAST Error: on VASTClient._buildAd, missing 'VASTAdTagURI' in wrapper

I guess this wrapper version is incompatible with the plugin or something.
Also got the cors header error in firefox you mentioned.

**Comment by bkolo** [comment]
Looks like it is just a Vast 2.0 versus 1.0 issue.  thanks.

**Comment by carpasse** [comment]
@bkolo thanks for the test tag. 

I will adapt the code so that it also works with your task.

**Comment by carpasse** [comment]
Sorry @bkolo VAST 3.0 and VAST 1.0 has quite some difference. I am very surprised somebody is still serving ads in VAST 1.0 since it is no longer supported by IAB. 

In the end we have decided not to support VAST 1.0.
