### ISSUE TITLE
Skip Ad button doesn't go away with VPaidJS (Possibly VPaidSWF)

### ISSUE THREAD

**Issue by nerdynick** [MailOnline/videojs-vast-vpaid#71]
When the vpaid pubslishes AdSkipped and/or AdStopped events after the Skip Ad Button is clicked. The button doesn't get removed.

**Comment by nerdynick** [comment]
I've dug into this further and this appears to be an even more interesting issue.  If the VPaid publishes multiple AdSkippableStateChange events. Multiple skip buttons are being placed on top of each other. Making it look like the button doesn't disappear when you click it as another one is right under it.

**Comment by carpasse** [comment]
Hi @nerdynick, 
You are right, we are not ready for this corner case I have already done a [commit with the fix](https://github.com/MailOnline/videojs-vast-vpaid/commit/bdca8185680ae24285ae69eabf4caacb4dcea520) that should fixes this issue.

I will do a release with the fix today or at the latest tomorrow.

Quick question, would you have been opened to do a PR with the fix?

**Comment by nerdynick** [comment]
Sweet, Glad to hear.

I try to do PullRequests if I can. Time and priorities are usually the dictators of that.

**Comment by carpasse** [comment]
@nerdynick  I just did a [release](https://github.com/MailOnline/videojs-vast-vpaid/releases/tag/0.1.20) with the fix for this bug.
I am closing the issue please reopen it if it doesn't work for you.
