### ISSUE TITLE
Do not restoring playback technology after FLV advert

### ISSUE THREAD

**Issue by astr0junk** [MailOnline/videojs-vast-vpaid#73]
After initialize videojs player tech is set on html. But then after playing flv advert (on flash mode) player do not restore html mode.

**Comment by carpasse** [comment]
@astr0junk do you have a test tag url? We have not experienced nor could reproduce the issue you commented.

**Comment by astr0junk** [comment]
@carpasse hello. I have this example for response stab: https://jsfiddle.net/54exc9L2/

**Comment by carpasse** [comment]
@astr0junk tried that that on our demo page and it worked flawlessly clicking on the skip ad and waiting for the ad to finish 

![screen shot 2015-10-08 at 16 42 59](https://cloud.githubusercontent.com/assets/1588321/10369677/c4831306-6ddb-11e5-89d2-648d3797ffd6.png)

**Comment by astr0junk** [comment]
@carpasse Yeap. and after ending videojs player do not restore Html Native player. It goes playig in flash mode cause videojs-vast-vpaid plugin remove from DOM html <video> object and not saved it in snapshot for example for restoring after adended event

**Comment by carpasse** [comment]
@astr0junk You are right!! that is weird. 

It seems that videojs is not handling well the change of sources and not applying the tech order.

We are going to take a look.
