### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by qlxucn** [MailOnline/videojs-vast-vpaid#78]
Hi, 

Seems there is no files like `videojs-vast-plugin.css` and `videojs-vast-plugin.min.js` in the `bin` folder. Do you mean `videojs-vast-vpaid.css` and `videojs-vast-vpaid.min.js`?

![Screenshot](https://api.monosnap.com/rpc/file/download?id=g4MdCz2xk5yu0Yd0ILs1XaEM7Iw0IO)

**Comment by carpasse** [comment]
@qlxucn Thanks for the issue. We really missed that when we changed the name of the plugin.
