### ISSUE TITLE
Configuration of ad response timeout

### ISSUE THREAD

**Issue by qlxucn** [MailOnline/videojs-vast-vpaid#79]
Hi,

Seems the option `responseTimeout` of `VPAIDAdUnitWrapper` is hardcoded as 5 seconds. Sometimes it's necessary to make it longer to increase ads fill rate. So is there anyway to override it from outside? Just like what `adsCancelTimeout` does.

Thanks.

![screenshot](https://api.monosnap.com/rpc/file/download?id=TrKEw7mEfRUpHCAlO6faQVOK4jJFzP)

**Comment by carpasse** [comment]
@qlxucn You are right this timer should be configurable. I have labeled the issue as an enhancement and we will try to solve it as soon as possible.

Wanna try doing the PR yourself?

**Comment by qlxucn** [comment]
@carpasse No problem, I will provide a PR after my work. Thanks.
