### ISSUE TITLE
Plugin doesn't work on IE8

### ISSUE THREAD

**Issue by qlxucn** [MailOnline/videojs-vast-vpaid#81]
Even the demo page doesn't work properly on IE8. Is IE8 not supported by this plugin? 

Please see screenshot for the issue.

![screenshot](https://api.monosnap.com/rpc/file/download?id=oh5wufvpjpkspjF6YYDA0bzbdJP27t)

**Comment by qlxucn** [comment]
Any ideas?

**Comment by Fetz** [comment]
If we fix an issue with IE8, with this commit:

https://github.com/MailOnline/videojs-vast-vpaid/commit/97195367b97aaa7213d1fa1d494656aa02477969

Check if this fix the issue fix the problem you having.

PS: I don't know if the demo is really working with IE8, but the code works in IE8 you can check some page of dailymail.co.uk with a video

**Comment by Fetz** [comment]
closing issue since no feedback was provided
