### ISSUE TITLE
Companion Ads

### ISSUE THREAD

**Issue by danielluong** [MailOnline/videojs-vast-vpaid#82]
Are companion ads supported?  I see references to companion ads in the source, but do not see it in the documentation or demo.

 More information in the VAST 3.0 Specifications on page 37 (http://www.iab.net/media/file/VASTv3.0.pdf)

**Comment by carpasse** [comment]
Hi @danielluong  I am sorry but companions ads are not supported they are not in the roadmap for the moment.

**Comment by alex-phillips** [comment]
@carpasse is there any possibility that you could instead provide an event when the final resolved VAST XML is parsed we could listen on? Maybe this callback could either provide the parsed VAST object, or worst case scenario the raw VAST XML itself and we could parse out and handle the companion ads ourselves?

**Comment by alex-phillips** [comment]
@carpasse I went ahead and opened a PR anyway (https://github.com/MailOnline/videojs-vast-vpaid/pull/113). I really hope you guys consider this. It simply allows the dev to access the information so that it is at least available.

(Tests included)
