### ISSUE TITLE
Conflict with mootools

### ISSUE THREAD

**Issue by qlxucn** [MailOnline/videojs-vast-vpaid#89]
Seems it conflicts with `mootools`.

Is there any way to work around?

![screenshot](https://api.monosnap.com/rpc/file/download?id=FbmWAJaaoZQT6qIa0lc25GrQ6LcfB6)

**Comment by Fetz** [comment]
I don't have much experience with mootools. If you still struggling can you send me a link with the issue (without the code minimized)

**Comment by massa84** [comment]
Closing as we didn't receive any reply for some time.
If you need further assistance please open a new issue. 
Thank you
