### ISSUE TITLE
Option for not start the video after preroll.

### ISSUE THREAD

**Issue by odimodugno** [MailOnline/videojs-vast-vpaid#93]
Hi,

I wanted to ask if it was useful add a new option for block the video start at the end of preroll or if is actually possible to do.

Thank you

**Comment by Fetz** [comment]
Yes is possible.

If you listen to the player event 'vast.contentStart' you can at that point pause the video

**Comment by Fetz** [comment]
Do you still need help with this issue?

**Comment by odimodugno** [comment]
no Thank you, sorry for late reply
