### ISSUE TITLE
Dynamic loading of plugin in iFrame -- Chrome -- Flash VPAID

### ISSUE THREAD

**Issue by joshmadewell** [MailOnline/videojs-vast-vpaid#94]
Hey guys,

I'm currently working on an implementation of the player that will live entirely in an iframe.

I'm creating the iframe element, appending the css, the videojs script, swfobject, and the plugin script all dynamically into the iframe, I'm then trying to install videojs into a `video` tag inside that iFrame but I'm getting the following error: 

`undefined vpaid flash load timeout 10000`

If I load the same code into firefox, im not getting the issue. This is leading me to believe that this may have something to do with Google Chrome throttling (or whatever they do to it) flash.

Have you guys experienced this and/or know of what's actually causing the issue and how to get around it?

I'm currently working on getting a demo page up so I can show you all the code but really hoping you have some insights.

Note: I've tried using the HTML5 tech instead of the Flash tech for the ad and got an error there as well:

`Uncaught VAST Error: VAST Error: on VPAIDHTML5Tech, invalid container HtmlElement`

for some reason it doesn't think that the video element is an HtmlElement?

Thanks for any help on this and I'll try to find time to get a demo available as soon as possible.

**Comment by indieveed** [comment]
Hi Josh,
We use the plugin in iframe on this page - http://www.sports.ru/videogallery/1034686761.html?video_id=1034686854#1034686854 and it works.
May be it could help you with your issue.

**Comment by joshmadewell** [comment]
@indieveed Here's an example of what we're doing. 

We're not setting the src of the iframe like you are in your example. Perhaps that's our problem?
```
<html>
    <head>
        <title>videojs-vast-vpaid iframe test</title>
        <script type="text/javascript" src="./node_modules/jquery/dist/jquery.min.js"></script>
    </head>
    <body>
        <script>
            var iframe = document.createElement('iframe');
            iframe.width = 430;
            iframe.height = 251;
            iframe.style.border = 'none';
            iframe.style.position = 'fixed';
            iframe.style.top = '0';
            iframe.style.left = '0';
            iframe.style['z-index'] = 9e10;

            var loadInOrder = function(resources, onAllLoaded) {
                function doSynchronousLoop(data, processData, done) {
                	if (data.length > 0) {
                		var loop = function(data, i, processData, done) {
                			processData(data[i], i, function() {
                				if (++i < data.length) {
                					loop(data, i, processData, done);
                				} else {
                					done();
                				}
                			});
                		};
                		loop(data, 0, processData, done);
                	} else {
                		done();
                	}
                }

                doSynchronousLoop(resources, function(data, i, callback) {
                    data.onload = callback;
                    iframe.contentWindow.document.head.appendChild(data);
                }, onAllLoaded);
            };

            iframe.onload = function() {
                var iframeDocument = iframe.contentWindow.document;

                var videoJsStylesheet = iframeDocument.createElement('link');
                videoJsStylesheet.rel = "stylesheet";
                videoJsStylesheet.type = "text/css";
                videoJsStylesheet.href = "./lib/video-js/video-js.min.css";

                var videojsCustomCss = iframeDocument.createElement('link');
                videojsCustomCss.rel = "stylesheet";
                videojsCustomCss.type = "text/css";
                videojsCustomCss.href = "./lib/videojs-vast-vpaid/bin/videojs-vast-vpaid.css";

                var videojsScript = iframeDocument.createElement('script');
                videojsScript.type = 'text/javascript';
                videojsScript.src = './lib/video-js/video.dev.js';

                var vastvpaidScript = iframeDocument.createElement('script');
                vastvpaidScript.type = 'text/javascript';
                vastvpaidScript.src = './lib/videojs-vast-vpaid/bin/videojs-vast-vpaid.js';

                var swfobject = iframeDocument.createElement('script');
                swfobject.type = 'text/javascript';
                swfobject.src = 'lib/videojs-vast-vpaid/bin/swfobject.js';

                $(iframe).contents().find('body')
                    .css({ margin: 0, padding: 0})
                    .append($('<div id="video-container"></div>')
                        .append($('<video id="player" class="video-js vjs-default-skin" controls preload="auto" height=251 width=430></video>')));

                loadInOrder([videoJsStylesheet, videojsCustomCss, videojsScript, vastvpaidScript, swfobject], function() {
                    iframe.contentWindow.videojs('player', {
                        controls: true,
                		plugins: {
                			vastClient:{
                				url: 'https://ad4.liverail.com/?LR_PUBLISHER_ID=1331&LR_SCHEMA=vast2-vpaid',
                				adCancelTimeout: 10000,
                				adsEnabled: true,
                				vpaidFlashLoaderPath: './lib/videojs-vast-vpaid/bin/VPAIDFlash.swf'
                			 }
                		}
                    }, function() {
                        this.play();
                    });
                });
            };

            document.body.appendChild(iframe);
        </script>
    </body>
</html>
```

**Comment by Fetz** [comment]
hey joshmadewell, can you create a page so i can debug better? cheers

**Comment by joshmadewell** [comment]
@Fetz 

Hey, no problem. Here's the demo: http://joshmadewell.com:9001/

Thank you for looking into this, I look forward to hearing what you find!

**Comment by Fetz** [comment]
I'm debugging your demo, but the weird thing is that the handshake (between flash and js) is not working.

What you can do is to try to put a bigger timeout and put debug true here:
https://github.com/MailOnline/videojs-vast-vpaid/blob/master/bin/videojs-vast-vpaid.js#L367

Another issue that we experience here is that newer versions of  chrome is forcing small flash to be blocked (the user need to click to allow the flash to run).

**Comment by joshmadewell** [comment]
Yeah, I'm thinking chrome must be blocking Flash here although I have tried all kinds of different sizes.

I'll try the debug flag but I'm really at a loss as to what can be done to fix this.

**Comment by Fetz** [comment]
The debug and 30 seconds is more so I can debug what error is being thrown in flash side.

**Comment by joshmadewell** [comment]
Oh, I got you man. For some reason I forgot that I'm hosting your debug for
you :D lol.

Sorry, I'll do that now!

**Comment by joshmadewell** [comment]
This is done, I set the timeout to 60 seconds, let me know if that's long enough or if you need longer!

**Comment by Fetz** [comment]
2 things is weird is that the flash is not showing anything but the moment I add a background style I can see the logging text (for some reason in chrome I can't use flash debugger so I create a textfield to log messages in debug mode).

this is the last logging I get: 
https://github.com/MailOnline/VPAIDFLASHClient/blob/master/flash/src/com/dailymail/vpaid/VPAIDFlash.as#L47

The weird part is that I don't get neither this logging:
https://github.com/MailOnline/VPAIDFLASHClient/blob/master/flash/src/com/dailymail/vpaid/VPAIDFlash.as#L211

Neither this:
https://github.com/MailOnline/VPAIDFLASHClient/blob/master/flash/src/com/dailymail/vpaid/VPAIDFlash.as#L57

I probably need to create a special flash with more logging. So I will later try do download your files and recreate in local environment.

**Comment by joshmadewell** [comment]
Awesome, thank you so much for looking into this! Please let me know if
there's anything I can do to help.

**Comment by joshmadewell** [comment]
@Fetz Have you had any more time to look into this issue? Thanks.

**Comment by Fetz** [comment]
Sorry the delay, I tried to check what is causing the problem with that but for some reason the handshake is not happening. Could be something specific with the new Chrome versions (security protection) causing some weird bug or could be a bug with the custom flash that Chrome is shipped...

**Comment by massa84** [comment]
Hi josh, I investigated the issue a bit and found the problem and the solution.
The problem was that videojs was pointing to an element inside the iframe but the initialisation function was executed in the main window. 
The vast plugin was then operating in the main window without any knowledge of what was happening inside the iframe (specifically couldn't communicate with the flash plugin as the event weren't propagating outside the iframe)

a safer way is to initialise videojs from inside the iframe
the iframe creation can also be simplified

```javascript
var iframe = document.createElement('iframe');
iframe.width = 430;
iframe.height = 251;
iframe.style.border = 'none';
iframe.style.position = 'fixed';
iframe.style.top = '0';
iframe.style.left = '0';
iframe.style['z-index'] = 9e10;

document.body.appendChild(iframe);

iframe.contentWindow.document.write('' +
    '<!DOCTYPE html>' +
    '<html lang="en">' +
    '<head>' +
        '<link  href="./lib/video-js.min.css" rel="stylesheet">' +
        '<script src="./lib/video.dev.js"></script>' +
        '<script src="./lib/swfobject.js"></script>' +
        '<link  href="./lib/videojs-vast-vpaid.css" rel="stylesheet">' +
        '<script src="./lib/videojs-vast-vpaid.js"></script>' +
    '</head>' +
    '<body>' +
        '<div id="video-container">' +
            '<video id="player" class="video-js vjs-default-skin" controls preload="auto" height=251 width=430></video>' +
        '</div>' +
        '<script>' +
            'videojs("player", {' +
                'controls: true,' +
                'plugins: {' +
                    'vastClient:{' +
                        'url: "http://vast.bp3863356.btrll.com/vast/3863356?n=1426410433&br_w=300&br_h=250&br_pageurl=blah",' + 
// i'm using this flash vast endpoint as yours was failing for a reason unrelated to the current problem
                        'adCancelTimeout: 30000,' +
                        'adsEnabled: true,' +
                        'vpaidFlashLoaderPath: "./lib/VPAIDFlash.swf"' +
                     '}' +
                '}' +
            '}, function() {' +
                'this.play();' +
            '});' +
        '</script>'+
    '</body>' +
    '</html>'
);
```

**Comment by joshmadewell** [comment]
@massa84 

Thank you so much for posting this.

I'm going to implement this today and let you know what I find!

**Comment by Fetz** [comment]
closing this issue. If is not working please reopen this issue

**Comment by ankurhora** [comment]
My vpaid ad fail to load in chrome through file:/// 
it says 
AD ERROR: undefined timeout
dont know what the reason might be

**Comment by massa84** [comment]
1 - do not reply with an unrelated comment to a CLOSED issue
2 - do not ask a question twice even though we already answered you https://github.com/MailOnline/videojs-vast-vpaid/issues/141
3 - you are not supposed to open the page directly from a file. Start a server and open from it otherwise it will not work. The instruction on the readme are clear enough :

...
If you want start the demo locally just run:
```
$ gulp start
```
and open the following link into your browser http://localhost:8086
...

after the demo run you can just edit the demo js files to try your code

**Comment by massa84** [comment]
@ankurhora Just some notes:
1 - do not reply with an unrelated comment to a CLOSED issue
2 - do not ask a question twice even though we already answered you here: https://github.com/MailOnline/videojs-vast-vpaid/issues/141
3 - do not ask the same question 3 times: https://github.com/MailOnline/videojs-vast-vpaid/issues/148 ! asking more than once will hardly change the answer.
4 - you are not supposed to open the page directly from a file. Start a server and open from it otherwise it will not work. The instruction on the readme should be clear enough :

...
If you want start the demo locally just run:
```
$ gulp start
```
and open the following link into your browser http://localhost:8086
...

after the demo run you can just edit the demo js files to try your code

**Comment by cwbeck** [comment]
this is such a terrible library. exact same issue - what a world of pain and the "fix" is horrible

**Comment by Fetz** [comment]
@cwbeck thank you for the constructive comment... If you check the documentation of [ExternalInterface](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/external/ExternalInterface.html) the communication between flash/js is through a global function, so is not something that I can control. The only thing that can be done is detecting if you are in the top frame and proxy it to another handler, but will work only if the iframe is friendly
