### ISSUE TITLE
DEMO HTML5

### ISSUE THREAD

**Issue by tscelles** [MailOnline/videojs-vast-vpaid#98]
I am working on a new demo with VPAID Javascript tags.
Do you have a guide for the files to be included for VPAID Javascript ? I want the demo to be compatible both with Vpaid Flash and Vpaid Javascript.

I looked after
http://mailonline.github.io/videojs-vast-vpaid/  but is too complex to understand what i need.

**Comment by Fetz** [comment]
All the files that need to be include are in the folder:

https://github.com/MailOnline/videojs-vast-vpaid/tree/master/bin

plus the code for videojs http://docs.videojs.com/docs/guides/setup.html

**Comment by Fetz** [comment]
@tscelles do you have still issues implementing the player?

**Comment by massa84** [comment]
Closing as we didn't receive any reply for some time.
If you need further assistance please open a new issue. 
Thank you

**Comment by darklordbzzz** [comment]
How can be page url delivered and CACHEBUSTING in players page url?
